---
#=============================================
# Author: Jonathan Ghebresilasie
# Created: 18/10/2023
#
# Description:
#
# Create a connection to 9k and run commands
# 
#
#=============================================

- hosts: nxos
  gather_facts: true
  connection: network_cli
  vars:
    ansible_ssh_user: admin
    ansible_ssh_pass: Admin_1234!
    ansible_network_os: nxos

  tasks:

    - name: include vars
      include_vars:
        file: ../group_vars/.cisco.yaml

    - name: Show version
      cisco.nxos.nxos_command:
        commands: show version
        wait_for: result[0] contains Cisco
      register: showversion

    - name: debug show version
      debug: 
        var: showversion

  # - name: Backup the config for {{ inventory_hostname }}
  #   tags: backup, install
  #   nxos_config:
  #     backup: yes
  #     backup_options:
  #       filename: "{{ inventory_hostname }}_backup.cfg"
  #       dir_path: ./backup
  #   register: config_output